### ISSUE TITLE
Should product's continuation take the entire result, or work like transform (as it does now)?

### ISSUE THREAD

**Issue by Quincunx271** [kvasir-io/mpl#54]
Currently, `product` calls its continuation once for each element in the result. This is unintuitive.

```c++
call<
    product<some_algorithm<>>,
    list<A, B>,
    list<C, D>
>
// produces:
list<
    some_algorithm<>::f<list<A, C>>>
    some_algorithm<>::f<list<A, D>>>
    some_algorithm<>::f<list<B, C>>>
    some_algorithm<>::f<list<B, D>>>
>
// what I was expecting:
some_algorithm<>::f<
    list<A, C>,
    list<A, D>,
    list<B, C>,
    list<B, D>
>
```

Currently, to get this behavior, one has to write: `fork<product<>, some_algorithm<>>`. If `product<>` is changed to call its continuation just once with all its arguments, to get the old behavior, one could write `product<transform<some_algorithm<>>>`

**Comment by chieltbest** [comment]
Product currently takes two arguments, one as the predicate for the individual results, and one for the overall continuation. To get the result you were expecting simply write `product<listify, some_algorithm<>>`. It might also be possible to make a case for `product<transform<unpack<some_algorithm<>>>`, but that would incur additional overhead, and we'd rather get the full performance rather than making such trade-offs.

**Comment by Quincunx271** [comment]
I see. I didn't understand this from the code / documentation, and I missed the overall continuation parameter when skimming.

**Comment by odinthenerd** [comment]
yeah docs need to be better, wish I had more hours in a day ;)
